### PR TITLE
Enh proper ssl certificate validation bypass

### PR DESCRIPTION
**Pull request by gst**
Since Python2.7.9 certitficates for SSL are more stricly validated by the ssl code.
This make self-signed certificates to now be rejected by default.
To still allow such certificate we have to provide an option for the user to fallback on the pre-2.7.9 behavior.

### CODE REVIEW

**Comment by gst** [comment]
NB: couldn't test myself, as doesn't have a python2.7.9 (could give it a try with 3.4.0 if sflvault is running ok with it).

And I think it will not be enough for expired server certificate .. which can also happens and you may want to also bypass.

so consider this as WIP and don't merge until agreed by .. well by agreement ;)

**Comment by gst** [comment]
nb: 
actually I've made it with 2 required options (one config file and one environment variable), I understood you wanted to have a supplementary config file option but it may not be the case...  just tell me. 
also if there is better (grammar and so on) for the install.txt added documentation then feel free to propose and I'll modify.

**Comment by cormier** [comment]
I'm not sure if @hsoft thinks the same, but I think we should only have one option, in the config file.

**Comment by gst** [comment]
simplified with only the config file option..

**Comment by gst** [comment]
gonna fix that stupid thing.. ;)

**Comment by hsoft** [comment]
Oops, sorry @gst, I *thought* that I could rebase your branch on `develop` and that the PR would update properly, but it looks like I've broken it.

I don't know if there's a way that you can change the target of this PR to `develop`, but otherwise, could you open a new PR please?

**Comment by hsoft** [comment]
Otherwise: I've tested that the feature works properly under Python 2.7.9. I also consider the implementation to be proper, so it would be good to merge into `develop`

**Comment by gst** [comment]
I've rebased (and squashed the 2 correction commits) on develop.

that's what you wanted ?

**Comment by cormier** [comment]
@gst This is it, but I think the target of this PR should be develop, not master :smile:

**Comment by gst** [comment]
new PR against develop here : https://github.com/savoirfairelinux/sflvault/pull/17

**Pull request closed without merging**
